import { useState } from "react";
import "./App.css";

type Activity = "workspace" | "agents" | "machines" | "canvas" | "git" | "search" | "settings";
type Panel = "Chat" | "Terminal" | "Runs" | "Logs";
const icons: Record<string, string> = { workspace:"▦", agents:"✦", machines:"◉", canvas:"◇", git:"⌘", search:"⌕", settings:"⚙", terminal:"›_", chat:"◌", runs:"↻", logs:"≡", split:"⊞", close:"×", more:"···", chevron:"›" };
const Icon = ({name}:{name:string}) => <span className="ico">{icons[name] ?? "·"}</span>;
const activities: {id:Activity; label:string}[] = [{id:"workspace",label:"Workspace"},{id:"agents",label:"Agents"},{id:"machines",label:"Machines"},{id:"canvas",label:"Canvas"},{id:"git",label:"Git"},{id:"search",label:"Search"},{id:"settings",label:"Settings"}];
const panels: Panel[] = ["Chat","Terminal","Runs","Logs"];

function Explorer({activity, select}:{activity:Activity;select:(name:string)=>void}) {
  if (activity === "machines") return <><h2>Machines</h2><Tree title="MacBook Pro" sub="macOS · Local" open items={["runtime · native", "sandboxes · 2", "models · 3"]}/><Tree title="Home Server" sub="Ubuntu · Offline" items={["RTX 5090", "models · 2"]}/></>;
  if (activity === "agents") return <><h2>Agents</h2><Tree title="Claude · Orchestrator" sub="sandbox: product-dev" open items={["running · 8m", "budget · $0.31"]}/><Tree title="Codex · Backend" sub="waiting for task"/><Tree title="Qwen Local · Research" sub="idle"/></>;
  if (activity === "canvas") return <><h2>Canvas</h2><p className="side-copy">Live relationships between workspaces, agents and tools will appear here.</p><button className="side-action" onClick={()=>select("Canvas")}>Open canvas <Icon name="chevron"/></button></>;
  if (activity === "git") return <><h2>Source control</h2><Tree title="main" sub="3 changed files" open items={["App.tsx", "App.css", "WORKBENCH_SHELL.md"]}/></>;
  if (activity === "search") return <><h2>Search</h2><input className="search-input" placeholder="Search workspace" autoFocus/><p className="side-copy">Search is a shell prototype.</p></>;
  if (activity === "settings") return <><h2>Settings</h2><Tree title="Workspace" sub="Local-first defaults"/><Tree title="Appearance" sub="Dark · system"/><Tree title="Security" sub="Review permissions"/></>;
  return <><h2>Workspace</h2><Tree title="Open Cube" sub="/Projects/open-cube" open items={["product-dev", "Claude · running", "Codex · waiting", "Terminal · active"]}/><Tree title="Design system" sub="/Projects/design-system"/><button className="side-action" onClick={()=>select("New session")}>+ New workspace</button></>;
}
function Tree({title,sub,items,open}:{title:string;sub:string;items?:string[];open?:boolean}) { return <div className="tree"><button className="tree-head"><span className={open?"tree-open":""}>›</span><i className={open?"dot running":"dot"}/><div><strong>{title}</strong><small>{sub}</small></div></button>{open && <div className="tree-children">{items?.map((item)=><button key={item}><span>{item.includes("Terminal")?"›_":"◇"}</span>{item}</button>)}</div>}</div>; }
function PanelView({panel}:{panel:Panel}) { if(panel === "Terminal") return <div className="terminal"><p><b>claude@product-dev</b> <span>~/open-cube</span></p><p>$ inspect workbench shell</p><p className="term-muted">Reading .ai/specs/WORKBENCH_SHELL.md</p><p className="term-muted">Building panel registry...</p><p><i>●</i> Ready for a provider runtime</p></div>; if(panel === "Runs") return <div className="run-list"><b>Claude · Workbench shell</b><span className="run"><i/> Running · 8m</span><p>Reading architecture and building shell prototype.</p><b>Qwen Local · UI audit</b><span className="muted">Idle · no runtime connected</span></div>; if(panel === "Logs") return <div className="terminal"><p className="term-muted">14:42:03 workspace loaded</p><p className="term-muted">14:42:05 mock state hydrated</p><p className="term-muted">14:42:07 inspector selection: Claude</p></div>; return <div className="chat"><div className="bubble assistant">I’m ready in <b>product-dev</b>. The workbench shell is using prototype data until <code>workbenchd</code> is implemented.</div><div className="bubble user">Build the agent workbench shell.</div><div className="thinking"><i/> Claude is reading the workspace specification…</div><div className="chat-box"><span>+</span><span className="placeholder">Message Claude</span><kbd>⌘ ↵</kbd><button>↑</button></div></div>; }

export default function App() { const [activity,setActivity]=useState<Activity>("workspace"); const [active,setActive]=useState<Panel>("Chat"); const [split,setSplit]=useState(false); const [inspector,setInspector]=useState(true); const [max,setMax]=useState(false); const [notice,setNotice]=useState(""); const addPanel=(p:Panel)=>{setActive(p);setSplit(true)}; return <main className={`workbench ${!inspector?"inspector-closed":""} ${max?"maximized":""}`}>
  <aside className="activity"><div className="cube">C</div>{activities.map(a=><button key={a.id} className={activity===a.id?"active":""} title={a.label} onClick={()=>setActivity(a.id)}><Icon name={a.id}/></button>)}<span/><button title="Open settings" onClick={()=>setActivity("settings")}><Icon name="settings"/></button><div className="user">RB</div></aside>
  <aside className="explorer"><header><div><span className="eyebrow">{activity}</span><h1>Open Cube</h1></div><button onClick={()=>setNotice("Command palette is planned for this shell.")}>⌘K</button></header><Explorer activity={activity} select={(value)=>setNotice(`${value} is a prototype action.`)}/><footer><i className="dot running"/> Prototype data · local only</footer></aside>
  <section className="centre"><header className="tabs"><div>{panels.map(p=><button className={active===p?"selected":""} key={p} onClick={()=>setActive(p)}><Icon name={p.toLowerCase()}/>{p}{active===p&&<span className="dirty">●</span>}</button>)}</div><div className="tab-actions"><button onClick={()=>setSplit(!split)} title="Split panel"><Icon name="split"/></button><button onClick={()=>setMax(!max)} title="Maximize panel">↗</button></div></header>{notice&&<div className="toast">{notice}<button onClick={()=>setNotice("")}>×</button></div>}<div className={split?"panel-grid split":"panel-grid"}><article className="panel"><PanelHeader panel={active} onAdd={addPanel}/><PanelView panel={active}/></article>{split&&<article className="panel"><PanelHeader panel="Terminal" onAdd={addPanel}/><PanelView panel="Terminal"/></article>}</div></section>
  {inspector&&<aside className="inspector"><header><span>INSPECTOR</span><button onClick={()=>setInspector(false)}>×</button></header><section><label>AGENT</label><h2>Claude</h2><p>Orchestrator · running</p></section><section><label>MODEL</label><strong>Claude Sonnet</strong><p>Provider connection not configured</p></section><section><label>SANDBOX</label><strong>product-dev</strong><p>Native sandbox · mock policy</p></section><section><label>MACHINE</label><strong>MacBook Pro</strong><p>macOS · local</p></section><section><label>PERMISSIONS</label><div className="permissions"><span>Files <b>workspace</b></span><span>Network <b>limited</b></span><span>Shell <b>enabled</b></span><span>Delegation <b>none</b></span></div></section></aside>}
  {!inspector&&<button className="show-inspector" onClick={()=>setInspector(true)}>Inspector</button>}<footer className="status"><span>⑂ main</span><span>◇ product-dev</span><span>✦ Claude Sonnet</span><span>◉ MacBook Pro</span><span><i/> 1 agent running</span><span className="push">12.4k tokens</span><span>$0.31</span></footer>
</main>; }
function PanelHeader({panel,onAdd}:{panel:Panel;onAdd:(p:Panel)=>void}) {return <header className="panel-header"><div><Icon name={panel.toLowerCase()}/><strong>{panel}</strong><span>product-dev · MacBook Pro</span></div><div><button onClick={()=>onAdd(panel==="Chat"?"Terminal":"Chat")}><Icon name="split"/></button><button><Icon name="more"/></button></div></header>}
